version: "2"
services:
  clientapi:
    build:
      context: .
      dockerfile: clientapi.Dockerfile
    ports:
      - "4449:4449"
    depends_on:
      - escrow
    extra_hosts:
      - "notary-server:127.0.0.1"
    networks:
      api:
      esc:
    entrypoint: clientapi
    command: -config=./fixtures/clientapi-server-config.toml 
  escrow:
    build:
      context: .
      dockerfile: escrow.Dockerfile
    networks:
      esc:
        aliases:
          - notaryescrow
    entrypoint: escrow
    command: -config=./fixtures/escrow-config-local.toml
networks:
  api:
    external: false
  esc:
    external: false
