version: "2"
services:
  clientapi:
    build:
      context: .
      dockerfile: clientapi.Dockerfile
    ports:
      - "4449:4449"
    depends_on:
      - escrow
    networks:
      esc:
    entrypoint: /usr/bin/env sh
    command: -c "clientapi -config=./fixtures/clientapi-server-config.toml"
  escrow:
    build:
      context: .
      dockerfile: escrow.Dockerfile
    networks:
      esc:
        aliases:
          - notaryescrow
    entrypoint: /usr/bin/env sh
    command: -c "escrow -config=./fixtures/escrow-config-local.toml"
networks:
  esc:
    external: false
