version: "2"
services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "8080:8080"
      - "4443:4443"
    networks:
      - server
    extra_hosts:
      - "notarysigner:172.31.19.180"
    dns: 8.8.8.8
    entrypoint: /usr/bin/env sh
    command: -c "./migrations/migrate.sh && notary-server -config=fixtures/server-config.json"
    depends_on:
      - mysql
  mysql:
    volumes:
      - ./notarysql/mysql-initdb.d:/docker-entrypoint-initdb.d
      - notary_data:/var/lib/mysql
    image: mariadb:10.1.10
    networks:
      - server
    environment:
      - TERM=dumb
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
    command: mysqld --innodb_file_per_table
volumes:
  notary_data:
    external: false
networks:
  server :
    external: false


