version: "2"
services:
  signer:
    build:
      context: .
      dockerfile: signer.Dockerfile
    ports:
      - "7899:7899"
#    networks:
#      sig:
#        aliases:
#          - notarysigner
    entrypoint: /usr/bin/env sh
    command: -c "notary-signer -config=fixtures/signer-config.json"
#    depends_on:
#      - mysql
#   mysql:
#     networks:
#       - sig
#     volumes:
#       - ./notarysql/mysql-initdb.d:/docker-entrypoint-initdb.d
#       - notary_data:/var/lib/mysql
#     image: mariadb:10.1.10
#     environment:
#       - TERM=dumb
#       - MYSQL_ALLOW_EMPTY_PASSWORD="true"
#     command: mysqld --innodb_file_per_table
# volumes:
#   notary_data:
#     external: false
# networks:
#  sig:
#    external: false
