version: "2"
services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "4443:4443"
    extra_hosts:
      - "notarysigner:172.31.3.144"
    dns: 8.8.8.8
    entrypoint: /usr/bin/env sh
    command: -c "notary-server -config=fixtures/server-config.json"
